<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button3</name>
   <tag></tag>
   <elementGuidId>685569d1-8884-49dc-8788-aa078a1dcf25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='c5844330-14ca-013d-174d-6e02b837b0cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c5844330-14ca-013d-174d-6e02b837b0cf</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'button success']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;foo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e36cc31e-fff2-4462-8c97-5fc9c573bbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c5844330-14ca-013d-174d-6e02b837b0cf</value>
      <webElementGuid>17954d2d-86b4-4450-bad5-9465760228ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button success</value>
      <webElementGuid>b4eb82ef-b5fe-4106-bb3b-cc16893deecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>foo</value>
      <webElementGuid>b31f4304-53b4-4f64-b5bf-df1924159c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c5844330-14ca-013d-174d-6e02b837b0cf&quot;)</value>
      <webElementGuid>b1e3a732-6b73-4b86-8465-c3e2ee56c9e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='c5844330-14ca-013d-174d-6e02b837b0cf']</value>
      <webElementGuid>160998c4-22f9-4f93-b97f-f1bbaf8aa635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[3]</value>
      <webElementGuid>5d02a056-95e7-40e4-9729-f4266e702676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'foo')]</value>
      <webElementGuid>75a9dbe2-a388-49db-9c61-44985dfbf78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[1]/following::a[1]</value>
      <webElementGuid>946f70d1-6786-4196-a9c4-6f395a3270ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/following::a[2]</value>
      <webElementGuid>6b5746bc-b60e-41ed-acbe-f720ead47c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[1]</value>
      <webElementGuid>12d570d6-8feb-463a-a41f-aafcfc4dc5ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ipsum'])[1]/preceding::a[1]</value>
      <webElementGuid>6a5d2a17-0816-43eb-840a-2c76b034eea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='foo']/parent::*</value>
      <webElementGuid>66e2b062-4aee-44e6-9e83-91a3df35e250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[4]</value>
      <webElementGuid>91cc42bb-bcb0-4f28-a0f8-5e6b141fb73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>29272683-b601-4cb4-905d-c7fc05c720ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'c5844330-14ca-013d-174d-6e02b837b0cf' and (text() = 'foo' or . = 'foo')]</value>
      <webElementGuid>1e9b2f80-56a4-424f-b816-410059adb603</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
