<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button2</name>
   <tag></tag>
   <elementGuidId>f875c79f-b0b5-46ba-b323-300a9623cc9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='c5812950-14ca-013d-174c-6e02b837b0cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c5812950-14ca-013d-174c-6e02b837b0cf</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'button alert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;qux&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32daaf4f-2fc5-46f1-a1a3-bbd512a350c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c5812950-14ca-013d-174c-6e02b837b0cf</value>
      <webElementGuid>1a40f9b0-7e23-4953-9ca4-1aaba7ee4c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alert</value>
      <webElementGuid>0aefeef9-2923-434b-bbbd-50535be53d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qux</value>
      <webElementGuid>7ad9337b-99a5-4a26-814b-3765742f3a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c5812950-14ca-013d-174c-6e02b837b0cf&quot;)</value>
      <webElementGuid>a025ae78-ba34-4e89-94d8-5716a7b7286d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='c5812950-14ca-013d-174c-6e02b837b0cf']</value>
      <webElementGuid>83397801-312d-4f89-8d75-bd729f83ce61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a[2]</value>
      <webElementGuid>7e8e4ab5-2cf0-4c89-869b-be41c018696f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'qux')]</value>
      <webElementGuid>b84a39f7-ada0-4200-8c58-c77295e10830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bar'])[1]/following::a[1]</value>
      <webElementGuid>95e79d6d-37ab-41a5-87f5-5926ad406ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[2]</value>
      <webElementGuid>81559252-c556-465f-9827-7bc954f6adbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[1]/preceding::a[1]</value>
      <webElementGuid>904be298-c184-457c-89de-6050c0df102d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lorem'])[1]/preceding::a[2]</value>
      <webElementGuid>2e6be108-3174-44e2-8916-bb46183c1d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='qux']/parent::*</value>
      <webElementGuid>87e017ef-0ef6-4302-ab52-e722edff135a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[3]</value>
      <webElementGuid>f9da80e1-52e1-4b0f-8ed3-7e3c63784895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>f2c7f0da-847f-4a25-bae0-b94370d6c38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'c5812950-14ca-013d-174c-6e02b837b0cf' and (text() = 'qux' or . = 'qux')]</value>
      <webElementGuid>f770775b-a8d6-4c25-ab89-cb35e7289c4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
