<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button1</name>
   <tag></tag>
   <elementGuidId>1796370e-6f3f-4218-b337-0bf1e050ee6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='c57db400-14ca-013d-174b-6e02b837b0cf']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#c57db400-14ca-013d-174b-6e02b837b0cf</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;bar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>269ae228-e8f1-4d5c-af07-a825c2a6d290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c57db400-14ca-013d-174b-6e02b837b0cf</value>
      <webElementGuid>2389b8ab-bd1f-4156-8f32-f32436c56e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf5891c6-6cc0-49b0-a937-5c9c5bc281a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bar</value>
      <webElementGuid>c75fc6ff-9103-4b79-a961-cf83828c227d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c57db400-14ca-013d-174b-6e02b837b0cf&quot;)</value>
      <webElementGuid>54710026-9c22-431f-b09b-a5ddc674a225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='c57db400-14ca-013d-174b-6e02b837b0cf']</value>
      <webElementGuid>e4fc7c24-49bf-4c3c-aff2-17b80f24a63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div/div/a</value>
      <webElementGuid>33f0df23-b1c2-4d61-9a88-403d38d00097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'bar')]</value>
      <webElementGuid>3270a7a6-f735-4674-a216-d8247540fd69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Challenging DOM'])[1]/following::a[1]</value>
      <webElementGuid>ed33eb43-a615-4868-854f-f508e00b770f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='qux'])[1]/preceding::a[1]</value>
      <webElementGuid>adbd7262-3f45-4ec3-80dc-60f27582311c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='foo'])[1]/preceding::a[2]</value>
      <webElementGuid>315b3a09-1501-4b83-89e1-e78cfba44d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bar']/parent::*</value>
      <webElementGuid>2837841a-194d-4d84-8709-14a1b39f2fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[2]</value>
      <webElementGuid>a56ef323-3762-4244-af1c-1401c8d8aa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>5b56aa10-f4d4-46c0-8023-2454ac1b345f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'c57db400-14ca-013d-174b-6e02b837b0cf' and (text() = 'bar' or . = 'bar')]</value>
      <webElementGuid>28430537-3f7c-4c1e-8a0b-932ca0503059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
